[package]
name = "gevulot-shim"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
